services:  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-volume: